[package]
name = "air-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
air-config.workspace = true
air-domain.workspace = true
air-github.workspace = true
air-merge.workspace = true
air-registry.workspace = true
air-storage.workspace = true
air-utils.workspace = true
air-workspace.workspace = true
semver.workspace = true
tokio.workspace = true

